import base64
import json
from typing import Optional

from Crypto.Cipher import AES
from Crypto.Random import get_random_bytes

from app.core.config import settings


def _get_aes_key() -> bytes:
    key = settings.AES_KEY.encode("utf-8")
    if len(key) not in (16, 24, 32):
        # Support hex-encoded 32-byte keys generated by token_hex(32).
        try:
            key = bytes.fromhex(settings.AES_KEY)
        except ValueError as exc:
            raise ValueError("AES_KEY must be 16/24/32-byte utf-8 or valid hex") from exc
    if len(key) not in (16, 24, 32):
        raise ValueError("AES_KEY must resolve to 16, 24, or 32 bytes")
    return key


def encrypt_payload(payload: Optional[dict]) -> Optional[str]:
    """Encrypt a JSON payload using AES-GCM and return a compact base64 token."""
    if payload is None:
        return None

    key = _get_aes_key()
    nonce = get_random_bytes(12)
    cipher = AES.new(key, AES.MODE_GCM, nonce=nonce)
    plaintext = json.dumps(payload, sort_keys=True).encode("utf-8")
    ciphertext, tag = cipher.encrypt_and_digest(plaintext)

    packed = nonce + tag + ciphertext
    return base64.b64encode(packed).decode("utf-8")
